In [28]:
import pandas as pd

In [29]:
df = pd.read_csv('scrap_data.csv')
df.head()

,ID,Nama,Harga,Deskripsi,Penjual,Lokasi,Rating,Rating 5,Rating 4,Rating 3,Rating 2,Rating 1,Terjual
0,339575556,Korset Melahirkan Pants Infrared 3in1 Korset P...,Rp55.000,Color :\n* Black\n* Cream\n\nMaterial :\n* 15%...,hotshaper,KOTA TANGERANG,4.6,7,2,1,0,0,22
1,842867812,Kaos Distro bahan combed 24s pria wanita anak ...,Rp99.000,ALLERT..!!\nPREMIUM PRODUCT ONLY 100%\n\n\n\nH...,rainbowpandaclothing,"KOTA SEMARANG - SEMARANG UTARA, JAWA TENGAH, ID",0.0,0,0,0,0,0,1
2,47241027,Seragam Paskibraka Paskibra Lengkap,Rp296.100,■Bahan Luar: Exclusive Gabardine.\nBahan yang ...,galerisantrikudus,KAB. KUDUS,4.9,189,12,2,0,1,"1,4RB"
3,848135372,KAOS WANITA/BAJU CEWEK OVERSIZE KINDNESS MATTE...,Rp45.000 - Rp59.000,"Hallo, Selamat datang di FRANCCES !\n\nKaos ka...",francess.id,KOTA JAKARTA BARAT,5.0,21,0,0,0,0,25
4,34613193,PREMIUM Baju renang muslim syar'i dewasa/ paka...,Rp186.000 - Rp315.000,Size \n\n\nM. ; Untuk berat badan 40- 48 kg...,ftswim,KOTA DEPOK,4.8,69,9,2,0,0,191

In [30]:
df['deskripsi'] = df['deskripsi'].replace('\n', ' ', regex=True)
df['rating'] = df['rating'].replace('Belum ada rating', 0)
df['terjual'] = df['terjual'].str.replace(',', '.').str.replace('RB', '00')
df['terjual'] = df['terjual'].str.replace('.','').str.replace('+','0')
df['harga'] = df['harga'].str.extract(r'(Rp[\d\.]+)') # tambah setelah +, [^\d]*$ Jika mau ambil sebelah kanan
df['harga'] = df['harga'].str.replace('Rp', '').str.replace('.','')

C:\Users\KeimalST\AppData\Local\Temp\ipykernel_9392\3872624579.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Terjual'] = df['Terjual'].str.replace('.','').str.replace('+','0')
C:\Users\KeimalST\AppData\Local\Temp\ipykernel_9392\3872624579.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Harga'] = df['Harga'].str.replace('Rp', '').str.replace('.','')

In [31]:
df.head()

,ID,Nama,Harga,Deskripsi,Penjual,Lokasi,Rating,Rating 5,Rating 4,Rating 3,Rating 2,Rating 1,Terjual
0,339575556,Korset Melahirkan Pants Infrared 3in1 Korset P...,55000,Color : * Black * Cream Material : * 15% Far ...,hotshaper,KOTA TANGERANG,4.6,7,2,1,0,0,22
1,842867812,Kaos Distro bahan combed 24s pria wanita anak ...,99000,ALLERT..!! PREMIUM PRODUCT ONLY 100% HALO K...,rainbowpandaclothing,"KOTA SEMARANG - SEMARANG UTARA, JAWA TENGAH, ID",0.0,0,0,0,0,0,1
2,47241027,Seragam Paskibraka Paskibra Lengkap,296100,■Bahan Luar: Exclusive Gabardine. Bahan yang b...,galerisantrikudus,KAB. KUDUS,4.9,189,12,2,0,1,1400
3,848135372,KAOS WANITA/BAJU CEWEK OVERSIZE KINDNESS MATTE...,45000,"Hallo, Selamat datang di FRANCCES ! Kaos katu...",francess.id,KOTA JAKARTA BARAT,5.0,21,0,0,0,0,25
4,34613193,PREMIUM Baju renang muslim syar'i dewasa/ paka...,186000,Size M. ; Untuk berat badan 40- 48 kg L ...,ftswim,KOTA DEPOK,4.8,69,9,2,0,0,191

In [32]:
df.dtypes

ID             int64
Nama          object
Harga         object
Deskripsi     object
Penjual       object
Lokasi        object
Rating       float64
Rating 5      object
Rating 4      object
Rating 3       int64
Rating 2       int64
Rating 1       int64
Terjual       object
dtype: object

In [33]:
df2 = df.to_csv('clean_data.csv', index = False)